# Generated by Django 4.2.21 on 2025-05-13 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_postvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(blank=True, help_text='Upload video file (supported formats: MOV, AVI, MP4, WEBM, MKV)', null=True, upload_to='post-videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mov', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Video File'),
        ),
    ]
