# Generated by Django 4.2.21 on 2025-05-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_alter_postvideo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='text1', max_length=500)),
                ('about', models.CharField(default='text1', max_length=500)),
                ('twitter', models.CharField(max_length=500)),
                ('facebook', models.CharField(max_length=500)),
                ('instagram', models.CharField(max_length=500)),
                ('open_days', models.CharField(default='text1', max_length=500)),
                ('newsletter', models.CharField(default='text1', max_length=500)),
                ('image1', models.ImageField(default='testimony.jpg', upload_to='footer')),
                ('image2', models.ImageField(default='testimony.jpg', upload_to='footer')),
                ('image3', models.ImageField(default='testimony.jpg', upload_to='footer')),
                ('image4', models.ImageField(default='testimony.jpg', upload_to='footer')),
                ('image5', models.ImageField(default='testimony.jpg', upload_to='footer')),
                ('image6', models.ImageField(default='testimony.jpg', upload_to='footer')),
            ],
        ),
    ]
