# Generated by Django 4.2.21 on 2025-05-15 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0006_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='gallery_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gallery',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
