# Generated by Django 4.2.21 on 2025-05-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0007_gallery_likes_gallery_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='image6',
        ),
        migrations.AddField(
            model_name='footer',
            name='email',
            field=models.CharField(default='text1', max_length=500),
        ),
        migrations.AddField(
            model_name='footer',
            name='phone',
            field=models.CharField(default='text1', max_length=500),
        ),
    ]
