# Generated by Django 4.2.21 on 2025-05-15 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0008_remove_footer_image1_remove_footer_image2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Footer', 'verbose_name_plural': 'Footer'},
        ),
        migrations.RemoveField(
            model_name='footer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='phone',
        ),
        migrations.AddField(
            model_name='footer',
            name='logo',
            field=models.ImageField(default='logo.png', help_text='Upload your logo', upload_to='footer/logo/'),
        ),
        migrations.CreateModel(
            name='FooterGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='testimony.jpg', upload_to='footer/gallery')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='artwork.footer')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
