# Generated by Django 4.2.21 on 2025-05-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0009_alter_footer_options_remove_footer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Footer', 'verbose_name_plural': 'Footer Settings'},
        ),
        migrations.RemoveField(
            model_name='footer',
            name='about',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='newsletter',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='open_days',
        ),
        migrations.AddField(
            model_name='footer',
            name='about_text',
            field=models.TextField(default=2, help_text='Short description about your company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='business_hours',
            field=models.TextField(blank=True, help_text='Enter your business hours', null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='company_name',
            field=models.CharField(default='Your Company Name', max_length=200),
        ),
        migrations.AddField(
            model_name='footer',
            name='copyright_text',
            field=models.CharField(default='© 2025. All Rights Reserved.', max_length=500),
        ),
        migrations.AddField(
            model_name='footer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='newsletter_text',
            field=models.CharField(default='Subscribe to our newsletter', max_length=500),
        ),
        migrations.AddField(
            model_name='footer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='youtube',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='facebook',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='instagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='twitter',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
