# Generated by Django 4.2.21 on 2025-05-17 13:27

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0010_alter_footer_options_remove_footer_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvideo',
            name='post',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='artwork.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=cloudinary.models.CloudinaryField(default=5, max_length=255, verbose_name='video'),
            preserve_default=False,
        ),
    ]
