# Generated by Django 4.2.21 on 2025-05-17 13:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0011_alter_postvideo_post_alter_postvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvideo',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_videos', to='artwork.post'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(blank=True, help_text='Upload video file (supported formats: MOV, AVI, MP4, WEBM, MKV)', null=True, upload_to='post-videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mov', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Video File'),
        ),
    ]
